export const AppText = {
  today: "Today",
  avatarInitials: "AK",
  clearDayTitle: "A clear day",
  clearDayMessage: "Nothing scheduled. Make space for something good.",
  newEvent: "New event",
  titleLabel: "TITLE",
  titlePlaceholder: "What are you planning?",
  startTimeLabel: "START TIME",
  colorLabel: "COLOR",
  addToCalendar: "Add to calendar",
  completed: "Completed",
  markComplete: "Mark as complete",
  calendarSuffix: "calendar",
  personal: "Personal",
  work: "Work",
  focus: "Focus",
  wellness: "Wellness",
  am: "AM",
  pm: "PM",
  completedPrefix: "✓  ",
  weekdays: ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"],
  months: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  events: {
    productStandup: "Product stand-up",
    designReview: "Design review",
    coffeeSarah: "Coffee with Sarah",
    deepWork: "Deep work",
    eveningRun: "Evening run",
    clientKickoff: "Client kickoff",
    lunch: "Lunch",
    interactionAudit: "Mobile interaction audit",
    weeklyPlanning: "Weekly planning",
    dentist: "Dentist",
  },
  locations: {
    googleMeet: "Google Meet",
    studioRoom: "Studio room",
    coffeeLab: "Coffee Lab",
    canalTrail: "Canal trail",
    zoom: "Zoom",
    cityDental: "City Dental",
  },
} as const;
